#!/bin/bash

# @file         HLL_Vision_Members_Judge
# @details      Used to judge vision members
# @author       ZhaoQicheng
# @vision       0.2.1

:<<!
JUST_HLL_VISION_MEMBERS:
        WeiHao
        Wangzihang
        DengJiaying
        ZhangMin
        ZhaoQicheng(TFW)
!

echo "

           ___   ___    ___   ________   ________               ___   ___    ___        ___
          /  /  /  /   /  /  /  _____/  /__   __/              /  /  /  /   /  /       /  /
         /  /  /  /   /  /  /  /____      /  /    _________   /  /__/  /   /  /       /  /
        /  /  /  /   /  /  /____   /     /  /    /________/  /   __   /   /  /       /  /
  _____/  /  /  /___/  /   ____/  /     /  /                /  /  /  /   /  /____   /  /____
 /_______/  /_________/  /_______/     /__/                /__/  /__/   /_______/  /_______/

"

#使用一个字符数组记录HLL战队视觉组成员姓名全拼
members=("weihao" "wangzihang" "zhaoqicheng" "dengjiaying" "zhangmin")
others=("tanxinglin" "liaolinzheng" "mazihan")

echo ${member[@]}
echo "此时航哥走了过来问你："

echo "就是你小子想查我们视觉的户口？输入[yes/no]"
read key1
if [ ${key1} == "yes" ]
then
        echo "王子航：你想查谁？说吧！"
fi

read name
echo "${name}？你确定？"

if [ ${name} == ${members[0]} ] || [ ${name} == ${members[1]} ] || [ ${name} == ${members[2]} ] || [ ${name} == ${members[3]} ] || [ ${name} == ${members[4]} ]
then
        echo "${name}是我们组的"
elif [ ${name} == ${others[0]} ] || [ ${name} == ${others[1]} ] || [ ${name} == ${others[2]} ] || [ ${name} == ${others[3]} ] || [ ${name} == ${others[4]}]
then
        echo "你不对劲，${name}就不是我们的人，你是条子！"
else
        echo "${name}不是我们组的"
        echo "此时王子航转过身给赵启程发了条消息"
        echo "有内鬼终止交易！"
fi

echo "王子航：你不对劲！HLL的水很深，你重开吧！"
